const MAX_WIDTH = 1200;
const MAX_HEIGHT = 800;
const PIXEL_SIZE = 25;
const WIDTH_PIXELS = MAX_WIDTH / PIXEL_SIZE;
const HEIGHT_PIXELS = MAX_HEIGHT / PIXEL_SIZE;

const TOTAL_PIXELS = (MAX_WIDTH/PIXEL_SIZE) * (MAX_HEIGHT/PIXEL_SIZE)

export {MAX_WIDTH, MAX_HEIGHT, PIXEL_SIZE, WIDTH_PIXELS, HEIGHT_PIXELS, TOTAL_PIXELS };
