on:
  push:
    branches:
      - release

jobs:
  build-push:
    runs-on: ubuntu-latest
    name: Builds Typescript
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Building Typescript
        uses: FuLagann/tsc-build-push@v1
        with:
          user-name: "Paul Koos"
          user-email: "paully_k5298@yahoo.com"
          message: "Automatically built unbuilt typescript"
          directories: src/ts/dist
